export const INSTITUCIONES: string[] = [
  "SENA",
  "Universidad Nacional de Colombia",
  "Universidad de Antioquia",
  "Universidad del Valle",
  "Universidad Javeriana",
  "Universidad de los Andes",
  "Universidad del Rosario",
  "Universidad EAN",
  "Universidad EAFIT",
  "Universidad Distrital Francisco José de Caldas",
  "Universidad de Cartagena",
  "Universidad del Atlántico",
  "Universidad Surcolombiana",
  "Universidad de Nariño",
  "Universidad de Córdoba",
  "Universidad de Caldas",
  "Universidad Tecnológica de Pereira",
  "Universidad Industrial de Santander",
  "Politécnico Grancolombiano",
  "Uniminuto",
  "Fundación Universitaria del Área Andina",
  "Universidad Autónoma de Colombia",
  "MinTIC",
  "Talento Tech",
  "Misión TIC",
  "Coursera",
  "Platzi",
  "Udemy",
  "LinkedIn Learning",
  "Google (certificación)",
  "Meta (certificación)",
  "Microsoft (certificación)",
  "AWS (certificación)",
  "IBM (certificación)",
];
